(deftheme chrome-devtools
  "Created 2018-04-24.")

(custom-theme-set-faces
 'chrome-devtools
 '(default ((t (:family "Hack" :foundry "outline" :width normal :height 108 :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#657b83" :background "#fdf6e3" :stipple nil :inherit nil))))
 '(cursor ((t (:inverse-video t :foreground "#fdf6e3" :background "#657b83"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((t (:foreground "#6c71c4"))))
 '(minibuffer-prompt ((t (:foreground "#657b83"))))
 '(highlight ((t (:background "#eee8d5"))))
 '(region ((t (:foreground "#fdf6e3" :background "#586e75"))))
 '(shadow ((t (:foreground "#93a1a1"))))
 '(secondary-selection ((t (:background "#eee8d5"))))
 '(trailing-whitespace ((t (:background "#dc322f"))))
 '(font-lock-builtin-face ((t (:slant normal :foreground "#657b83"))))
 '(font-lock-comment-delimiter-face ((t (:slant normal :foreground "#93a1a1"))))
 '(font-lock-comment-face ((t (:foreground "#93a1a1"))))
 '(font-lock-constant-face ((t (:weight bold :foreground "#268bd2"))))
 '(font-lock-doc-face ((t (:slant normal :foreground "#2aa198"))))
 '(font-lock-function-name-face ((t (:foreground "#268bd2"))))
 '(font-lock-keyword-face ((t (:foreground "#859900"))))
 '(font-lock-negation-char-face ((t (:weight bold :foreground "#b58900"))))
 '(font-lock-preprocessor-face ((t (:foreground "#268bd2"))))
 '(font-lock-regexp-grouping-backslash ((t (:weight bold :foreground "#859900"))))
 '(font-lock-regexp-grouping-construct ((t (:weight bold :foreground "#b58900"))))
 '(font-lock-string-face ((t (:foreground "#2aa198"))))
 '(font-lock-type-face ((t (:foreground "#b58900"))))
 '(font-lock-variable-name-face ((t (:foreground "#268bd2"))))
 '(font-lock-warning-face ((t (:weight bold :inherit (error)))))
 '(button ((t (:underline (:color foreground-color :style line)))))
 '(link ((t (:weight bold :underline (:color foreground-color :style line) :foreground "#b58900"))))
 '(link-visited ((t (:weight normal :underline (:color foreground-color :style line) :foreground "#b58900"))))
 '(fringe ((t (:foreground "#93a1a1" :background "#fdf6e3"))))
 '(header-line ((t (:underline (:color "#eee8d5" :style line) :overline nil :box (:line-width 2 :color "#fdf6e3" :style unspecified) :foreground "#657b83" :background "#fdf6e3"))))
 '(tooltip ((t (:foreground "#7B6000" :background "#DEB542" :inherit (variable-pitch)))))
 '(mode-line ((t (:underline (:color "#cccec4" :style line) :overline "#eee8d5" :box (:line-width 1 :color "#eee8d5" :style unspecified) :foreground "#657b83" :background "#eee8d5"))))
 '(mode-line-buffer-id ((t (:weight bold :foreground "#586e75"))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((((class color) (min-colors 88)) (:box (:line-width 2 :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:underline (:color "#cccec4" :style line) :overline "#eee8d5" :box (:line-width 1 :color "#fdf6e3" :style unspecified) :foreground "#93a1a1" :background "#fdf6e3"))))
 '(isearch ((t (:weight normal :foreground "#fdf6e3" :background "#d33682"))))
 '(isearch-fail ((t (:weight bold :foreground "#dc322f" :background "#fdf6e3"))))
 '(lazy-highlight ((t (:weight normal :foreground "#fdf6e3" :background "#b58900"))))
 '(match ((t (:weight bold :foreground "#586e75" :background "#eee8d5"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'chrome-devtools)
